//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetLibrary.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scenario
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public int OrderStage { get; set; }
        public Nullable<int> ID_type_scenario { get; set; }
        public Nullable<int> ID_action { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual TypeScenario TypeScenario { get; set; }
    }
}
